version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["--auth", "false"]

volumes:
  mongo-data:
